### ISSUE TITLE
Review group 7

### ISSUE THREAD

**Issue by nymann** [bierproductie/management#50]

**Comment by Joergenson** [comment]
Review the following document:
[Project Proposal.pdf](https://github.com/bierproductie/management/files/5339806/Project.Proposal.pdf)

**Comment by Joergenson** [comment]
# Layout

”*It's fine, it looks like your average Microsoft Word document. 
Your front page is decent, but it lacks your signatures 
(we think this is required).*” - Kristian Nymann, 2020

# Document structure

Please keep the following points in mind when proof-reading the entire document.
Be sure to have tense consistency (present/past tense). This mistake is made in 
the Background section (“In order to do that the brewery was…..”). We may have 
missed others. A spell check using grammarly would benefit the report greatly. 
There are a few misconceptions regarding a/an as well as are/is.
Some sentences are very long, for example the first sentence under the 
“Stakeholders” section. Another important point is to avoid using personal 
pronouns (we, us, etc.)

# Approval rating

## 1. Background
The background section looks good. It gives a good understanding of the problem, 
as well as a short introduction to the solution the group will provide. 

## 2. Stakeholders
Overall the stakeholders section looks fine. The first sentence is very long and 
could potentially be shortened. Proofreading would also benefit here: 
“the **first** one being…”.

## 3. Aims
The first sentence doesn’t give a good indication of what the aim is. Instead 
start the sentence from: “The aim of the project is to…”. Don’t write which 
tech-stacks you want to use (HTML, JavaScript, NodeJS). Instead write something 
like: “This project aims to offer an interactive web interface for monitoring, 
controlling and adjusting the brewery machine”.
Also, “monitor of **outputs** and **sensors**” are the same 
(The sensors provide an output)

## 4. Objectives
Objectives are the solution you want with a focus on the technical part. So 
point 3 in the list is a fine technical Objective. The first points:
1. To identify the overall requirements for the prototype 
(included in the project description)
2. To specify the most important detailed requirements

Aren’t specific technical requirements.


## 5. Solutions
It is our understanding that this section should specify how you are going to 
implement the system. This can be expressed with a system design diagram. Also, 
specify whether you plan on using other languages.


## 6. Initial requirements analysis
Overall this section looks good. In the list of requirements, you could give the 
requirements IDs (R01, R02, etc). Your use case diagram states that MES is an 
actor to the system the group is developing, but aren’t we supposed to make the 
MES? Making it the actual system (the square/box) and not an actor?

## 7. Related research
As far as we have understood it, you don’t have to write any theory about the 
related research. Instead, you can mention the related research, so the reader 
knows what theory is needed to understand the report.


## 8. Methods
Good section with a few small notes. Call Visual Studio Code an IDE instead of a 
software. This is a more correct terminology. It’s good that you give a short 
introduction to some of the different applications you will use. It helps give 
the reader an overview of how the group will work during development.
Why do Unified Process and ARsim have their own subsections, but the other ones 
don’t?

## 9. Risks
Looks good

## 10. Organization
The Organization section looks good. However, you could add a few extra things. 
What are the advantages of Pair Programming? (why will you use it?). Also add 
“branch” after master under GitHub.

## 11. Milestones and project plan
Is expected work hours pr. person??

## 12. Deliverables
This section looks good. Not sure if the UML diagram should be here. Perhaps 
it’s better to have the UML diagram in the “Solutions” section.

## 13. Tentative outline for the project report
Overall the section looks good. The outline itself looks fine. However, the part 
about overleaf doesn’t really belong in this section. Perhaps move it to the 
Methods or Organization section?

**Comment by kepet19** [comment]
[Uploading group_7_review_by_group_5.pdf…]()

**Comment by Joergenson** [comment]
[group_7_review_by_group_5.pdf](https://github.com/bierproductie/management/files/5350644/group_7_review_by_group_5.pdf)

**Comment by Joergenson** [comment]
![image](https://user-images.githubusercontent.com/55147377/95499456-95a7fb80-09a5-11eb-9d45-12cb67211c68.png)
Confirmation of deliverance of the review by mail.
